デザインを変更してみましたわ
jiro4989/ojosama-web pull request #10
Opened 2022-07-01 14:58 UTC by Shinaco1992

画像を作成して当て込んでみましたわ。
それに伴って色や間隔の微調整を行いましたわ。

html/templateを利用した書き方がよくわからなかったので、既存のmeta_head.tmpl.htmlにゴリゴリと書き足す形になりました。
また、静的ファイルの取得方法がわからず、画像用ディレクトリを用意してそこに画像を置いて読み込むといったことができませんでした… :confounded:
そのため、データURLにエンコードして画像を読み込ませております。

少々荒々しい形になってしまいましたが、もしお気に召しましたら採用していただけますと嬉しいですわ。

2022-07-02 00:46 UTC, jiro4989 commented
ありがとうございますわ～～❗❗💯💯💯
今少々見る時間がありませんので、また後ほど確認いたしますわ！
今しばらくお待ちになってくださいまし！

2022-07-02 12:52 UTC, jiro4989 commented
確認いたしましたわ❗
なんと可愛らしいデザイン・・・❗❗
私感動いたしましたわ～～💯💯💯

ぜひともおマージ✨したいところですが、

> また、静的ファイルの取得方法がわからず、画像用ディレクトリを用意してそこに画像を置いて読み込むといったことができませんでした… 😖

こちらについて回答いたしますわね

2022-07-02 13:13 UTC, jiro4989 commented
私からのレビューは以上でございますわ❗
ご確認お願いいたしますわ🙏🙏🙏

2022-07-02 13:46 UTC, Shinaco1992 commented
ご確認ありがとうございます❗ 
しかし、申し訳ございません、回答が…確認すべき内容が…見つからないですわ…😨 
わたくしの目が節穴の可能性もございまして、Githubに慣れていないこともあり、見つけられていないのかもしれません…
お手数おかけしますが、ご確認いただけますようお願いいたしますわ 🙇

2022-07-02 13:53 UTC, jiro4989 commented
あら・・・？
お使いの端末が違うからでしょうか・・・？
PCで画面を表示して、リロードしてみても表示されませんこと？

2022-07-02 13:54 UTC, jiro4989 commented
あら、本当ですわね、プライベートモードで画面を表示したら見れませんわね...

2022-07-02 13:54 UTC, jiro4989 requested changes

2022-07-02 13:54 UTC, jiro4989 commented on public/views/parts/meta_head.tmpl.html
> +  background: repeat url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAAFUCAYAAABoYNNoAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAuLSURBVHgB7d07ch3HFQbguSAWoG0ocJW8Ay7
私の方でも確認いたしましたところ、おっしゃるとおりお画像ファイルを配置してからファイルパスを指定しても取得できませんでしたわ。
これは使用しているGoのWebフレームワークの echo のデフォルトの仕様のようですの。

echo のおドキュメントの [Static Files | Echo](https://echo.labstack.com/guide/static-files/) を見るに、明示的に静的ファイルのパスを紐づけてあげないと参照できないようですの。

（おそらくセキュリティ上の理由で、おカレントディレクトリ配下のおファイルを何でも参照できると危ないから、明示的に指定させるようにしてるのだと思いますの）

ですので、静的ファイルを参照できるようにGoのコードの修正が必要ですわ。
以下の箇所を修正してみてくださいまし。

https://github.com/Shinaco1992/ojosama-web/blob/change-design/main.go#L41

```diff
         e := echo.New()
+        e.Static("/assets", "public/assets")
         env := newEnv()
```

これで `public/assets` 配下の静的ファイルを参照できるようになりますわ。

そして、以下のディレクトリ構造で画像ファイルを配置してみてくださいまし。

```
+ public/
  + views/
  | + index.tmpl.html
  | + ...
  |
  + assets/          <-- New!
    + images/        <-- New!
      + ****.png ... <-- New!
```

このように、 public ディレクトリ配下に `assets/images` ディレクトリを追加して、以下のようにファイルを参照することで、画像を読み込めるようになると思いますわ。

```css
  background: repeat url("/assets/images/なんとかかんとか.png"), #513439;
```

2022-07-02 13:56 UTC, jiro4989 commented
申し訳ございませんわ～～！！！
Request Changesを送信しわすれてましたわ～～！！！
私クソザコエンジニアでしたわ～～！！！！

2022-07-02 13:58 UTC, Shinaco1992 commented on public/views/parts/meta_head.tmpl.html
> +  background: repeat url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAAFUCAYAAABoYNNoAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAuLSURBVHgB7d07ch3HFQbguSAWoG0ocJW8Ay7
ありがとうございます❗ 
ディレクトリ構成も。大変助かりますわ🙏 
上記の内容で修正いたしますわ✨

2022-07-03 04:14 UTC, Shinaco1992 commented
@jiro4989 
昨日ご教示いただきました内容をもとに修正いたしましたわ ❗ 

- 画像を追加いたしました。
- cssも別途ファイルを切り出して、読み込むようにいたしました。

それから、どうしても改変したい過去があり、強制プッシュいたしました…。
他の方の作業に影響ない認識で行いましたが、、本来ご法度でありますゆえ、大変申し訳ございません 🙇 
こちらはコードの編集内容自体は変わっておりません。

ご確認のほどよろしくお願いいたしますわ 🙏

2022-07-03 04:39 UTC, jiro4989 approved these changes

2022-07-03 04:42 UTC, jiro4989 commented
確認いたしましたわ～～❗❗❗
とってもとっても壱百満点ですわ❗❗💯💯💯
LGTMですわ✨✨

2022-07-03 04:42 UTC, merged